;/*!modules/conf.jsx*/
define("modules/conf.jsx",function(e,t,o){"use strict";o.exports={Router:ReactRouter.Router,Route:ReactRouter.Route,IndexRoute:ReactRouter.IndexRoute,DATABASE:[]}});
;/*!modules/action/searchAction.jsx*/
define("modules/action/searchAction.jsx",function(e,c,s){"use strict";s.exports=Reflux.createActions(["search"])});
;/*!modules/component/header.jsx*/
define("modules/component/header.jsx",function(e,t,a){"use strict";var n=e("modules/action/searchAction.jsx");a.exports=React.createClass({displayName:"exports",getInitialState:function(){return{skinData:[],skintoggle:"none"}},changeSkin:function(e,t){var a=e;document.body.style.backgroundImage="url(img/skin/big_"+a+".jpg)",document.body.style.backgroundRepeat="noRepeat",document.body.style.backgroundPosition="center 0",document.body.style.backgroundSize="cover",document.body.style.backgroundAttachment="fixed";for(var n=t.target.parentElement.parentElement.children,c=0;c<n.length;c++)n[c].style.borderColor="#FFF";t.target.parentElement.style.borderColor="#000"},skin:function(){return this.state.skinData.map(function(e,t){return React.createElement("li",{key:t,onClick:this.changeSkin.bind(this,e.id)},React.createElement("img",{src:"img/skin/"+e.src,alt:""}),React.createElement("p",null,e.title))}.bind(this))},skintoggle:function(){this.setState("none"===this.state.skintoggle?{skintoggle:"block"}:{skintoggle:"none"})},sure:function(){this.setState({skintoggle:"none"})},defaultTo:function(){this.setState({skintoggle:"none"}),document.body.style.background="#ccc"},navClick:function(e){$(this.refs.nav).children().css({background:"transparent",color:"#000"}),$(e.target).css({background:"#1db69a",color:"#fff"})},search:function(){n.search(this.refs.searchValue.value),console.log(this.refs.searchValue.value),ReactRouter.hashHistory.replace("/more/"+this.refs.searchValue.value),$(this.refs.nav).children().css({color:"#000",background:"transparent"}),$(this.refs.more).css({background:"#1db69a",color:"#fff"})},keysearch:function(e){13===e.keyCode&&this.search()},render:function(){return React.createElement("div",{className:"container"},React.createElement("div",{className:"top",style:{display:this.state.skintoggle}},React.createElement("ul",null,this.skin(),React.createElement("button",{id:"sure",onClick:this.sure},"确定"),React.createElement("button",{id:"default",onClick:this.defaultTo},"使用默认皮肤"))),React.createElement("header",null,React.createElement("h1",{className:"logo"},React.createElement("a",{href:""},React.createElement("img",{src:"img/logo.png"}))),React.createElement("input",{onKeyDown:this.keysearch,type:"text",placeholder:"摔跤吧！爸爸",ref:"searchValue",id:"search"}),React.createElement("button",{onClick:this.search},"搜一搜"),React.createElement("a",{onClick:this.skintoggle},"换肤")),React.createElement("div",{className:"nav"},React.createElement("nav",{onClick:this.navClick,ref:"nav"},React.createElement("a",{href:"#/"},"首页"),React.createElement("a",{href:"#/film"},"电影"),React.createElement("a",{href:"#/tv"},"电视剧"),React.createElement("a",{href:"#/vairety"},"综艺"),React.createElement("a",{href:"#/comic"},"动漫"),React.createElement("a",{href:"#/play"},"娱乐"),React.createElement("a",{href:"#/more/全部",ref:"more"},"更多"))))},componentDidMount:function(){$.get("data/skin.json",function(e){e&&0===e.errno&&this.setState({skinData:e.data})}.bind(this))}})});
;/*!modules/component/footer.jsx*/
define("modules/component/footer.jsx",function(e,t,l){"use strict";l.exports=React.createClass({displayName:"exports",render:function(){return React.createElement("section",{className:"footer"},React.createElement("div",{className:"footerBox"},React.createElement("div",{className:"left"},React.createElement("img",{src:"img/logo.png",alt:""}),React.createElement("span",null,"Copyright © 360安全网址. All Rights Reserved."),React.createElement("span",null,"浙ICP证B2-20090064号   信息网络传播视听节目许可证1109357号")),React.createElement("div",{className:"right"},React.createElement("ul",null,React.createElement("li",null,React.createElement("p",null,"扫码下载APP")),React.createElement("li",null,React.createElement("img",{src:"img/link.png",alt:""}))),React.createElement("ul",null,React.createElement("li",null,"服务"),React.createElement("li",null,"加入收藏"),React.createElement("li",null,"意见反馈"),React.createElement("li",null,"官方微博"),React.createElement("li",null,"联系方式")),React.createElement("ul",null,React.createElement("li",null,"关于"),React.createElement("li",null,"关于我们"),React.createElement("li",null,"版权声明"),React.createElement("li",null,"用户协议")))))}})});
;/*!modules/app.jsx*/
define("modules/app.jsx",function(e,t,o){"use strict";var n=e("modules/component/header.jsx"),l=e("modules/component/footer.jsx");o.exports=React.createClass({displayName:"exports",getInitialState:function(){return{toggle:"none"}},gotopScroll:function(){this.setState($(window).scrollTop()>=1500?{toggle:"block"}:{toggle:"none"})},gotop:function(){window.scrollTo(0,0)},render:function(){return React.createElement("section",null,React.createElement(n,null),this.props.children,React.createElement("span",{className:"gotop",onClick:this.gotop,style:{display:this.state.toggle}},"返回顶部"),React.createElement(l,null))},componentDidMount:function(){window.addEventListener("scroll",this.gotopScroll)}})});
;/*!modules/component/chart.jsx*/
define("modules/component/chart.jsx",function(e,t,n){"use strict";n.exports=React.createClass({displayName:"exports",getInitialState:function(){return{list:[]}},createList:function(){return this.state.list.map(function(e,t){return React.createElement("li",{key:t},React.createElement("span",{className:"num"},t+1),React.createElement("a",null,e.name),React.createElement("span",null,e.num+"万"))})},render:function(){return React.createElement("div",{className:"chart"},React.createElement("h3",null,"观看榜"),React.createElement("ul",null,this.createList()))},componentDidMount:function(){$.get("data/chart.json",function(e){e&&0===e.errno&&this.setState({list:e.data})}.bind(this))}})});
;/*!modules/component/class.jsx*/
define("modules/component/class.jsx",function(e,t,n){"use strict";n.exports=React.createClass({displayName:"exports",getDefaultProps:function(){return{list:["1.jpg","2.jpg","3.jpg","4.jpg","5.jpg","6.jpg","7.jpg","8.jpg"]}},createList:function(){return this.props.list.map(function(e,t){return React.createElement("li",{key:t},React.createElement("a",null,React.createElement("img",{src:"img/banner/"+e,alt:""})))})},render:function(){return React.createElement("section",{className:"class"},React.createElement("h3",null,"精彩专题"),React.createElement("ul",null,this.createList()))}})});
;/*!modules/component/sortby.jsx*/
define("modules/component/sortby.jsx",function(e,t,r){"use strict";r.exports=React.createClass({displayName:"exports",getDefaultProps:function(){return{typelist:["军事","古装","谍战","喜剧","言情","伦理","都市","历史","警匪","神话"],adresslist:["内地","香港","台湾","美国","韩国"],superlist:["胡歌","孙俪","baby","杨幂","王凯"]}},createTypelist:function(){return this.props.typelist.map(function(e,t){return React.createElement("li",{key:t},React.createElement("a",{href:"#/more/电影"},e))})},createAdresslist:function(){return this.props.adresslist.map(function(e,t){return React.createElement("li",{key:t},React.createElement("a",{href:"#/more"},e))})},createSuperlist:function(){return this.props.superlist.map(function(e,t){return React.createElement("li",{key:t},React.createElement("a",{href:"#/more"},e))})},render:function(){return React.createElement("section",{className:"sortby"},React.createElement("h3",null,"选你喜欢"),React.createElement("a",{href:"#/more",className:"more"},"更多 >"),React.createElement("ul",null,this.createTypelist()),React.createElement("ul",null,this.createAdresslist()),React.createElement("ul",null,this.createSuperlist()))}})});
;/*!modules/component/pageAside.jsx*/
define("modules/component/pageAside.jsx",function(e,t,n){"use strict";var s=e("modules/component/chart.jsx"),c=e("modules/component/class.jsx"),a=e("modules/component/sortby.jsx");n.exports=React.createClass({displayName:"exports",render:function(){return React.createElement("section",{className:"pageAside"},React.createElement(s,null),React.createElement(c,null),React.createElement(a,null))}})});
;/*!modules/component/page2.jsx*/
define("modules/component/page2.jsx",function(e,t,a){"use strict";a.exports=React.createClass({displayName:"exports",createList:function(){return this.state.list.map(function(e,t){return React.createElement("li",{key:t},React.createElement("img",{src:"img/list/"+e.url}),React.createElement("img",{src:"img/bg.png",className:"bg"}),React.createElement("span",null,e.score),React.createElement("p",{className:"title"},e.title),React.createElement("p",{className:"subtitle"},e.subtitle),React.createElement("p",{className:"num"},e.num))})},getDefaultProps:function(){return{getType:"",titleVal:"",typelist:["军事","古装","谍战","喜剧","言情","伦理","都市","历史","警匪","神话"]}},getInitialState:function(){return{list:[]}},createMoreList:function(){return this.props.typelist.map(function(e,t){return React.createElement("a",{href:"#/more",key:t},e)})},render:function(){return React.createElement("section",{className:"page2"},React.createElement("h3",null,this.props.titleVal),React.createElement("a",{href:"#/more",className:"more"},"更多"),React.createElement("span",{className:"link"},this.createMoreList()),React.createElement("ul",{style:{height:"670px"}},this.createList()))},componentDidMount:function(){$.get("data/"+this.props.getType+".json",function(e){e&&0===e.errno&&this.setState({list:e.data})}.bind(this))}})});
;/*!modules/component/update.jsx*/
define("modules/component/update.jsx",function(t,e,s){"use strict";s.exports=React.createClass({displayName:"exports",getDefaultProps:function(){return{week:["周一","周二","周三","周四","周五","周六","周日"]}},getInitialState:function(){return{list:[],list1:[],list2:[],list3:[],list4:[],list5:[],list6:[],list7:[]}},enter:function(t){for(var e=t.target.parentElement.children,s=0;s<e.length;s++)e[s].style.background="#FFF",e[s].style.color="#000";t.target.style.background="#1db69a",t.target.style.color="#fff",this.setState("周一"===t.target.text?{list:this.state.list1}:"周二"===t.target.text?{list:this.state.list2}:"周三"===t.target.text?{list:this.state.list3}:"周四"===t.target.text?{list:this.state.list4}:"周五"===t.target.text?{list:this.state.list5}:"周六"===t.target.text?{list:this.state.list6}:{list:this.state.list7})},createWeek:function(){return this.props.week.map(function(t,e){return React.createElement("a",{key:e,onMouseEnter:this.enter},t)}.bind(this))},createList:function(){return this.state.list.map(function(t,e){return React.createElement("li",{key:e},React.createElement("img",{src:"img/update/"+t.url}),React.createElement("img",{src:"img/bg.png",className:"bg"}),React.createElement("p",{className:"title"},t.title),React.createElement("p",{className:"subtitle"},t.subtitle))})},render:function(){return React.createElement("section",{className:"update"},React.createElement("h3",null,"动态直播"),React.createElement("span",null,this.createWeek()),React.createElement("ul",null,this.createList()))},componentDidMount:function(){$.get("data/update.json",function(t){t&&0===t.errno&&(this.setState({list1:t.data.list1,list2:t.data.list2,list3:t.data.list3,list4:t.data.list4,list5:t.data.list5,list6:t.data.list6,list7:t.data.list7}),this.setState({list:this.state.list1}))}.bind(this))}})});
;/*!modules/component/page.jsx*/
define("modules/component/page.jsx",function(t,e,a){"use strict";a.exports=React.createClass({displayName:"exports",createList:function(){return this.state.list.map(function(t,e){return React.createElement("li",{key:e},React.createElement("img",{src:"img/"+t.url}),React.createElement("img",{src:"img/bg.png",className:"bg"}),React.createElement("span",null,t.score),React.createElement("p",{className:"title"},t.title),React.createElement("p",{className:"subtitle"},t.subtitle),React.createElement("p",{className:"num"},t.num))})},getDefaultProps:function(){return{data:{titleVal:"",type:""}}},getInitialState:function(){return{list:[],list1:[],list2:[],moretoggle:!0}},more:function(){this.setState(this.state.moretoggle?{list:this.state.list2,moretoggle:!1}:{list:this.state.list1,moretoggle:!0})},render:function(){return React.createElement("section",{className:"page",id:this.props.data.id},React.createElement("h3",null,this.props.data.titleVal),React.createElement("span",{className:"more",onClick:this.more},"换一换"),React.createElement("ul",null,this.createList()))},componentDidMount:function(){$.get("data/home.json",function(t){t&&0===t.errno&&(this.setState({list1:t.data,list2:t.datamore}),this.setState({list:this.state.list1}))}.bind(this))}})});
;/*!modules/page/film.jsx*/
define("modules/page/film.jsx",function(e,t,a){"use strict";var l=e("modules/component/pageAside.jsx"),n=e("modules/component/page2.jsx"),c=e("modules/component/update.jsx"),m=e("modules/component/page.jsx");a.exports=React.createClass({displayName:"exports",render:function(){return React.createElement("section",{className:"film"},React.createElement(l,null),React.createElement(n,{titleVal:"每日电影",getType:"film"}),React.createElement(c,null),React.createElement(m,{data:{titleVal:"电影速递"}}),React.createElement(n,{titleVal:"热门电影",getType:"film"}))}})});
;/*!modules/page/tv.jsx*/
define("modules/page/tv.jsx",function(e,t,a){"use strict";var l=e("modules/component/pageAside.jsx"),n=e("modules/component/page2.jsx"),c=e("modules/component/update.jsx"),s=e("modules/component/page.jsx");a.exports=React.createClass({displayName:"exports",render:function(){return React.createElement("section",{className:"tv"},React.createElement(l,null),React.createElement(n,{titleVal:"每日TV",getType:"tv"}),React.createElement(c,null),React.createElement(s,{data:{titleVal:"电影速递"}}),React.createElement(n,{titleVal:"热门TV",getType:"tv"}))}})});
;/*!modules/page/vairety.jsx*/
define("modules/page/vairety.jsx",function(e,t,a){"use strict";var l=e("modules/component/pageAside.jsx"),n=e("modules/component/page2.jsx"),c=e("modules/component/update.jsx"),s=e("modules/component/page.jsx");a.exports=React.createClass({displayName:"exports",render:function(){return React.createElement("section",{className:"vairety"},React.createElement(l,null),React.createElement(n,{titleVal:"每日综艺",getType:"vairety"}),React.createElement(c,null),React.createElement(s,{data:{titleVal:"电影速递"}}),React.createElement(n,{titleVal:"热门综艺",getType:"vairety"}))}})});
;/*!modules/page/comic.jsx*/
define("modules/page/comic.jsx",function(e,t,c){"use strict";var a=e("modules/component/pageAside.jsx"),l=e("modules/component/page2.jsx"),n=e("modules/component/update.jsx"),o=e("modules/component/page.jsx");c.exports=React.createClass({displayName:"exports",render:function(){return React.createElement("section",{className:"comic"},React.createElement(a,null),React.createElement(l,{titleVal:"每日动漫",getType:"comic"}),React.createElement(n,null),React.createElement(o,{data:{titleVal:"电影速递"}}),React.createElement(l,{titleVal:"热门动漫",getType:"comic"}))}})});
;/*!modules/page/play.jsx*/
define("modules/page/play.jsx",function(e,t,a){"use strict";var l=e("modules/component/pageAside.jsx"),n=e("modules/component/page2.jsx"),c=e("modules/component/update.jsx"),s=e("modules/component/page.jsx");a.exports=React.createClass({displayName:"exports",render:function(){return React.createElement("section",{className:"Play"},React.createElement(l,null),React.createElement(n,{titleVal:"每日娱乐",getType:"play"}),React.createElement(c,null),React.createElement(s,{data:{titleVal:"电影速递"}}),React.createElement(n,{titleVal:"热门娱乐",getType:"play"}))}})});
;/*!modules/action/filterAction.jsx*/
define("modules/action/filterAction.jsx",function(e,t,i){"use strict";i.exports=Reflux.createActions(["filter"])});
;/*!modules/component/filter.jsx*/
define("modules/component/filter.jsx",function(e,t,n){"use strict";var r=e("modules/action/filterAction.jsx");n.exports=React.createClass({displayName:"exports",filter:function(e){for(var t=e.target.parentElement.children,n=[],a=0;a<t.length;a++)t[a].style.background="#FFF",t[a].style.color="#000";e.target.style.background="#1db69a",e.target.style.color="#FFF",$(this.refs.ul).find("a").each(function(){"rgb(29, 182, 154)"===this.style.background&&n.push(this.text)}),r.filter(n)},createSubList:function(e){return e.map(function(e,t){return React.createElement("a",{key:t,onClick:this.filter},e)}.bind(this))},createList:function(){return this.props.list.map(function(e,t){return React.createElement("li",{ref:"li",key:t},React.createElement("span",null,e.type,"  :  "),React.createElement("span",null,this.createSubList(e.name)))}.bind(this))},getDefaultProps:function(){return{list:[{type:"频道",name:["全部","电视剧","电影","综艺","动漫"]},{type:"类型",name:["全部","军事","古装","谍战","喜剧","言情","伦理","都市","历史","警匪","神话"]},{type:"年代",name:["全部","2017","2016","2015","2014"]},{type:"地区",name:["全部","内地","香港","台湾","美国","韩国"]},{type:"明星",name:["全部","胡歌","孙俪","baby","杨幂","王凯"]}]}},render:function(){return React.createElement("section",{className:"filter"},React.createElement("ul",{ref:"ul"},this.createList()))}})});
;/*!modules/store/searchStore.jsx*/
define("modules/store/searchStore.jsx",function(e,A,t){"use strict";var s=e("modules/action/searchAction.jsx"),i=e("modules/conf.jsx");t.exports=Reflux.createStore({listenables:[s],onSearch:function(e){for(var A=[],t=0;t<i.DATABASE.length;t++)(i.DATABASE[t].title.indexOf(e)>=0||i.DATABASE[t].subtitle.indexOf(e)>=0||i.DATABASE[t].type.indexOf(e)>=0||i.DATABASE[t].adress.indexOf(e)>=0||i.DATABASE[t].all.indexOf(e)>=0)&&A.push(i.DATABASE[t]);this.trigger(A)}})});
;/*!modules/store/filterStore.jsx*/
define("modules/store/filterStore.jsx",function(e,t,r){"use strict";var s=e("modules/conf.jsx"),o=e("modules/action/filterAction.jsx");r.exports=Reflux.createStore({listenables:[o],onFilter:function(e){for(var t=s.DATABASE,r=[],o=0;o<e.length;o++){for(var l=0;l<t.length;l++)(t[l].num===e[o]||t[l].type===e[o]||t[l].all===e[o]||t[l].adress===e[o])&&r.push(t[l]);t=r,r=[]}this.trigger(t)}})});
;/*!modules/component/result.jsx*/
define("modules/component/result.jsx",function(t,e,s){"use strict";var a=t("modules/conf.jsx"),n=t("modules/store/searchStore.jsx"),c=t("modules/store/filterStore.jsx");s.exports=React.createClass({displayName:"exports",mixins:[Reflux.connect(n,"list"),Reflux.connect(c,"list")],getDefaultProps:function(){return{text:[]}},getInitialState:function(){return{data:"",startList:[],list:[]}},createList:function(){return this.state.list.map(function(t,e){return React.createElement("li",{key:e,className:"resuliLi"},React.createElement("i",{id:"i"},t.type,t.adress),React.createElement("img",{src:"img/list/"+t.url}),React.createElement("img",{src:"img/bg.png",className:"bg"}),React.createElement("span",null,t.score),React.createElement("p",{className:"title"},t.title),React.createElement("p",{className:"subtitle"},t.subtitle),React.createElement("span",{className:"good"},t.good,"观看"),React.createElement("p",{className:"num"},t.num))})},Sort:function(t){$(t.target).parent().find("span").css({background:"transparent",color:"#000"}),$(t.target).css({background:"#1db69a",color:"#fff"}),this.setState("热门"===$(t.target).text()?{list:this.state.list.sort(function(t,e){return e.good-t.good})}:{list:this.state.list.sort(function(t,e){return e.score-t.score})})},render:function(){return React.createElement("div",{className:"result",style:{minHeight:"800px"}},React.createElement("h3",null,"看你所看"),React.createElement("div",{className:"sortdiv"},React.createElement("span",{className:"hot",ref:"hot",onClick:this.Sort},"热门"),React.createElement("span",{className:"score",onClick:this.Sort},"评分")),React.createElement("ul",null,this.createList()))},componentDidMount:function(){$.get("data/list.json",function(t){a.DATABASE=t.data,t&&0===t.errno&&(this.setState({startList:t.data}),this.setState({list:this.state.startList}))}.bind(this))}})});
;/*!modules/page/more.jsx*/
define("modules/page/more.jsx",function(e,t,n){"use strict";var s=e("modules/component/filter.jsx"),o=e("modules/component/result.jsx"),r=e("modules/action/searchAction.jsx");n.exports=React.createClass({displayName:"exports",getInitialState:function(){return{text:[]}},render:function(){return React.createElement("section",{className:"more"},React.createElement(s,null),React.createElement(o,null))},componentDidMount:function(){r.search(this.props.params.query)},componentDidUpdate:function(){r.search(this.props.params.query)}})});
;/*!modules/component/banner.jsx*/
define("modules/component/banner.jsx",function(t,e,n){"use strict";n.exports=React.createClass({displayName:"exports",getDefaultProps:function(){return{list:["1.jpg","2.jpg","3.jpg","4.jpg","5.jpg","6.jpg","7.jpg","8.jpg"]}},getInitialState:function(){return{timer:function(){},list:["1.jpg","2.jpg","3.jpg","4.jpg","5.jpg","6.jpg","7.jpg","8.jpg"]}},createList:function(){return this.props.list.map(function(t,e){return React.createElement("li",{key:e},React.createElement("a",null,React.createElement("img",{src:"img/banner/"+t,alt:""})))})},left:function(){var t=this.state.list,e=t.pop();t.unshift(e);var n=parseInt(t[0].slice(0,1)),s=$(this.refs.ul).children();s.css({border:"none"}),s.eq(n-1).css({border:"5px solid green"}),this.setState({list:t})},right:function(){var t=this.state.list,e=t.shift();t.push(e);var n=parseInt(t[0].slice(0,1)),s=$(this.refs.ul).children();s.css({border:"none"}),s.eq(n-1).css({border:"5px solid green"}),this.setState({list:t})},render:function(){return React.createElement("section",{className:"banner"},React.createElement("div",null,React.createElement("img",{src:"img/banner/"+this.state.list[0],alt:""}),React.createElement("ul",{ref:"ul"},this.createList())),React.createElement("span",{className:"left",onClick:this.left},"<"),React.createElement("span",{className:"right",onClick:this.right},">"))},componentDidMount:function(){this.setState({timer:setInterval(function(){this.right()}.bind(this),2e3)})},componentWillUnmount:function(){clearInterval(this.state.timer)}})});
;/*!modules/component/aside.jsx*/
define("modules/component/aside.jsx",function(e,t,n){"use strict";n.exports=React.createClass({displayName:"exports",getDefaultProps:function(){return{showHide:"none"}},getInitialState:function(){return{list:[]}},go:function(e){$(this.refs.ul).children().children().css({background:"transparent"}),$(e.target).css({background:"#1db69a"})},createList:function(){return this.state.list.map(function(e,t){return React.createElement("li",{key:t,onClick:this.go},React.createElement("a",{href:"#"+e.type},e.name))}.bind(this))},show:function(){},render:function(){return React.createElement("div",{className:"aside",ref:"aside",style:{display:this.props.showHide}},React.createElement("h3",null,"导航"),React.createElement("ul",{ref:"ul"},this.createList()))},componentDidMount:function(){$.get("data/Aside.json",function(e){e&&0===e.errno&&this.setState({list:e.data})}.bind(this))}})});
;/*!modules/page/home.jsx*/
define("modules/page/home.jsx",function(t,e,a){"use strict";var l=t("modules/component/banner.jsx"),i=t("modules/component/aside.jsx"),n=t("modules/component/page.jsx");a.exports=React.createClass({displayName:"exports",getInitialState:function(){return{toggle:"none",title:{hot:{titleVal:"热点聚焦",id:"1"},film:{titleVal:"经典电影",id:"2"},tv:{titleVal:"好看的电视剧",id:"3"},play:{titleVal:"全民娱乐",id:"4"},comic:{titleVal:"热血动漫",id:"5"},Vairety:{titleVal:"综艺频道",id:"6"}}}},getScroll:function(){this.setState($(window).scrollTop()>=500&&$(window).scrollTop()<=3400?{toggle:"block"}:{toggle:"none"})},render:function(){return React.createElement("section",{className:"home"},React.createElement(l,null),React.createElement(i,{showHide:this.state.toggle}),React.createElement(n,{data:this.state.title.hot}),React.createElement(n,{data:this.state.title.film}),React.createElement(n,{data:this.state.title.tv}),React.createElement(n,{data:this.state.title.play}),React.createElement(n,{data:this.state.title.comic}),React.createElement(n,{data:this.state.title.Vairety}))},componentDidMount:function(){window.addEventListener("scroll",this.getScroll)},componentWillUnmount:function(){window.removeEventListener("scroll",this.getScroll)}})});
;/*!modules/router/routers.jsx*/
define("modules/router/routers.jsx",function(e,t,o){"use strict";var a=e("modules/conf.jsx").Router,m=e("modules/conf.jsx").Route,c=e("modules/conf.jsx").IndexRoute,n=e("modules/app.jsx"),s=e("modules/page/film.jsx"),l=e("modules/page/tv.jsx"),p=e("modules/page/vairety.jsx"),r=e("modules/page/comic.jsx"),u=e("modules/page/play.jsx"),d=e("modules/page/more.jsx"),x=e("modules/page/home.jsx");o.exports=React.createElement(a,null,React.createElement(m,{path:"/",component:n},React.createElement(m,{path:"film",component:s}),React.createElement(m,{path:"tv",component:l}),React.createElement(m,{path:"vairety",component:p}),React.createElement(m,{path:"comic",component:r}),React.createElement(m,{path:"play",component:u}),React.createElement(m,{path:"more/:query",component:d}),React.createElement(c,{component:x})))});
;/*!modules/bootstrap.jsx*/
define("modules/bootstrap.jsx",function(e){"use strict";var r=e("modules/router/routers.jsx");ReactDOM.render(r,app)});
;/*!modules/action/filteraction.jsx*/
define("modules/action/filteraction.jsx",function(e,t,i){"use strict";i.exports=Reflux.createActions(["filter"])});